const COUNTER_INCREMENT = "COUNTER_INCREMENT";
const COUNTER_DECREMENT = "COUNTER_DECREMENT";
const COUNTER_REST = "COUNTER_REST";

export {
    COUNTER_INCREMENT,
    COUNTER_DECREMENT,
    COUNTER_REST,
}